name: mapbox_api
description: Unofficial Mapbox Dart SDK that follow official Mapbox documentation.
version: 1.0.0
homepage: https://github.com/stafyniaksacha/mapbox-api

dependencies:
  http: ^1.2.0

dev_dependencies:
  lints: ^5.0.0

environment:
  sdk: '>=2.12.0 <3.0.0'